import {Editor} from '@tiptap/core';
import StarterKit from '@tiptap/starter-kit';
import Placeholder from '@tiptap/extension-placeholder';
import {TextStyleKit} from '@tiptap/extension-text-style';
import TextAlign from '@tiptap/extension-text-align';
import Image from '@tiptap/extension-image';
import {TableKit} from '@tiptap/extension-table';
import {Fragment} from '@tiptap/pm/model';
import {closeHistory} from '@tiptap/pm/history';
import {TextSelection,NodeSelection} from '@tiptap/pm/state';
import {defaults,palettes,cleanStyle,validImageUrl,encode,decode} from './codec.js';
import {safeHTML,sanitizeHTML,toMarkdown,fontFamilies} from './content.js';
import {createAtmospheres,original} from './atmospheres.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const atmospheres=createAtmospheres({getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)});
let activeAtmosphereId=atmospheres.defaultId();
let style=atmospheres.get(activeAtmosphereId).style,timer,reading=null,imagePosition=null,atmosphereDraft=null,editingAtmosphereId=null;
function notify(message){$('#notice').textContent=message;clearTimeout(timer);timer=setTimeout(()=>$('#notice').textContent='',6000)}
function invalidate(){$('#share-result').hidden=true;$('#share-url').value=''}
const LetterImage=Image.extend({addAttributes(){return {...this.parent?.(),imageWidth:{default:100,parseHTML:n=>parseFloat(n.style.width)||100,renderHTML:a=>({style:`width:${Math.max(10,Math.min(100,a.imageWidth))}%`})},imageAlign:{default:'center',parseHTML:n=>n.style.marginLeft==='auto'?(n.style.marginRight==='auto'?'center':'right'):'left',renderHTML:a=>({style:`margin-left:${a.imageAlign==='left'?'0':'auto'};margin-right:${a.imageAlign==='right'?'0':'auto'}`})},imageRadius:{default:0,parseHTML:n=>parseFloat(n.style.borderRadius)||0,renderHTML:a=>({style:`border-radius:${Math.max(0,Math.min(60,a.imageRadius))}px`})}}}});
const emptyLetter='<h1></h1><p></p>';
const editor=new Editor({element:$('#editor'),extensions:[StarterKit.configure({heading:{levels:[1,2,3]},link:{openOnClick:false,autolink:true,protocols:['http','https','mailto'],HTMLAttributes:{rel:'noopener noreferrer',target:'_blank'}}}),TextStyleKit,TextAlign.configure({types:['heading','paragraph']}),LetterImage,TableKit.configure({table:{resizable:false}}),Placeholder.configure({showOnlyCurrent:false,includeChildren:true,placeholder:({editor,node,pos})=>{const index=editor.state.doc.resolve(pos).index(0);if(index===0&&node.type.name==='heading'&&node.attrs.level===1)return 'Una carta para ti';if(index===1&&node.type.name==='paragraph')return 'Empieza redactando.';return ''}})],content:emptyLetter,editorProps:{attributes:{'aria-label':'Título y contenido de tu carta',role:'textbox','aria-multiline':'true',spellcheck:'true'},transformPastedHTML:sanitizeHTML},onUpdate(){updateUI();invalidate()},onSelectionUpdate(){updateUI()}});
function escapeHTML(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editableHTML(d){const body=safeHTML(d.markdown);return d.title?`<h1>${escapeHTML(d.title)}</h1>${body||'<p></p>'}`:(body||emptyLetter)}
function serializableHTML(){const root=document.createElement('div');root.innerHTML=editor.getHTML();const emptyBlock=node=>['H1','H2','H3','P'].includes(node.tagName)&&!node.textContent.trim()&&!node.querySelector('img,table,hr');while(root.firstElementChild&&emptyBlock(root.firstElementChild))root.firstElementChild.remove();while(root.lastElementChild&&emptyBlock(root.lastElementChild))root.lastElementChild.remove();return root.innerHTML}
function hasLetterContent(){return Boolean(serializableHTML().trim())}
function updateUI(){const text=editor.getText().trim();$('#count').textContent=(text?text.split(/\s+/u).length:0)+' palabras';$$('[data-command]').forEach(b=>{const c=b.dataset.command;b.classList.toggle('is-active',editor.isActive(c));b.setAttribute('aria-pressed',String(editor.isActive(c)));if(c==='undo'||c==='redo')b.disabled=!editor.can()[c]()});$('#block').value=editor.isActive('heading')?'h'+editor.getAttributes('heading').level:'p';$('#table-tools').hidden=!editor.isActive('table');const a=editor.getAttributes('textStyle');$('#selection-font').value=(a.fontFamily||'').replace(/["']/g,'');$('#selection-size').value=parseFloat(a.fontSize)||'';$('#text-align').value=editor.getAttributes('paragraph').textAlign||editor.getAttributes('heading').textAlign||'left';}
function pageBackground(){switch(style.background){case'gradient':return `linear-gradient(135deg,${style.pageBg},${style.pageEnd})`;case'radial':return `radial-gradient(ellipse at 50% 0%,${style.pageEnd},${style.pageBg} 75%)`;case'lines':return `repeating-linear-gradient(135deg,${style.pageBg} 0px,${style.pageBg} 12px,${style.pageEnd} 13px,${style.pageBg} 14px)`;case'image':return style.backgroundImage?`linear-gradient(#0004,#0004),url(${JSON.stringify(style.backgroundImage)})`:'none';default:return'none'}}
function applyStyle(){style=cleanStyle(style);const props={'--accent':style.color,'--letter-bg':style.transparent?'transparent':style.paperBg,'--letter-text':style.textColor,'--letter-font':fontFamilies[style.font],'--letter-size':style.size+'px','--paper-padding':style.padding+'px','--paper-width':style.width+'px','--paper-radius':style.radius+'px','--paper-border':style.border?`${style.borderWidth}px ${style.borderStyle} ${style.borderColor}`:'0px solid transparent','--paper-shadow':style.shadow?`0 16px 65px rgba(0,0,0,${style.shadow/100})`:'none','--letter-leading':style.lineHeight,'--paragraph-gap':style.paragraphSpace+'px','--title-color':style.titleColor,'--title-size':style.titleSize+'px','--title-font':fontFamilies[style.titleFont],'--title-align':style.titleAlign,'--page-bg':style.pageBg,'--page-image':pageBackground(),'--page-space':style.pageSpace+'px','--paper-left':style.align==='left'?'0':'auto','--paper-right':style.align==='right'?'0':'auto'};for(const [k,v]of Object.entries(props))document.documentElement.style.setProperty(k,v);document.body.classList.toggle('no-ornaments',!style.ornaments);document.body.classList.toggle('no-border',!style.border);$$('[data-ornament]').forEach(n=>n.textContent=style.ornament);$('.reader-sign').hidden=!style.signature;$$('[data-style]').forEach(n=>{if(n.type==='checkbox')n.checked=style[n.dataset.style];else n.value=style[n.dataset.style]});$$('[data-output]').forEach(n=>{const input=$(`[data-style="${n.dataset.output}"]`);n.textContent=style[n.dataset.output]+' '+input.dataset.suffix});refreshAtmospheres();}
$$('[data-style]').forEach(input=>{const event=input.type==='url'?'change':'input';input.addEventListener(event,()=>{const k=input.dataset.style;let value=input.type==='checkbox'?input.checked:input.type==='range'?Number(input.value):input.value;if(k==='backgroundImage'&&value&&!validImageUrl(value)){notify('Usa una URL completa de imagen que empiece por https:// o http://.');return}style[k]=value;applyStyle();invalidate()})});
function refreshAtmospheres(){
 const list=$('#atmosphere-list');list.replaceChildren();
 for(const preset of atmospheres.list()){
  const button=document.createElement('button');button.type='button';button.className='theme';button.dataset.atmosphereId=preset.id;button.classList.toggle('selected',preset.id===activeAtmosphereId);button.setAttribute('aria-pressed',String(preset.id===activeAtmosphereId));
  const sample=document.createElement('span');sample.className='sample';sample.style.background=preset.style.paperBg;sample.style.color=preset.style.textColor;sample.style.borderColor=preset.style.color;sample.style.fontFamily=fontFamilies[preset.style.font];sample.textContent='Aa ';
  const symbol=document.createElement('small');symbol.textContent=preset.style.ornament;symbol.style.color=preset.style.color;sample.append(symbol);
  const name=document.createElement('span');name.textContent=preset.name;button.append(sample,name);button.title=preset.name+(preset.id===atmospheres.defaultId()?' · Al empezar':'');
  if(preset.id===atmospheres.defaultId()){const badge=document.createElement('span');badge.className='atmosphere-badge';badge.textContent='Al empezar';button.append(badge)}
  button.onclick=()=>{activeAtmosphereId=preset.id;style={...preset.style};applyStyle();invalidate()};list.append(button);
 }
 const selected=atmospheres.get(activeAtmosphereId);const dirty=selected&&JSON.stringify(selected.style)!==JSON.stringify(cleanStyle(style));
 $('#atmosphere-current').textContent=selected?selected.name+(dirty?' · cambios sin guardar en la atmósfera':' · diseño guardado'):(style.atmosphereName||'Atmósfera compartida')+' · puedes guardarla como nueva';
 $('#edit-atmosphere').disabled=!selected;$('#update-atmosphere').disabled=!selected;$('#remove-atmosphere').disabled=!selected;
 $('#remove-atmosphere').textContent=original(activeAtmosphereId)?'Restaurar original':'Eliminar atmósfera';
}
function applySaved(result,message){activeAtmosphereId=result.preset.id;style={...result.preset.style};applyStyle();invalidate();notify(result.persisted?message:'Aplicada para esta sesión. El navegador bloqueó el guardado de atmósferas; conserva el enlace de tu carta.')}
function updateAtmospherePreview(){const draft=atmosphereDraft;const preview=$('#atmosphere-mini');preview.style.background=`linear-gradient(135deg,${draft.pageBg},${draft.pageEnd})`;const paper=preview.firstElementChild;paper.style.background=draft.paperBg;paper.style.color=draft.textColor;paper.style.borderColor=draft.borderColor;paper.style.fontFamily=fontFamilies[draft.font];$('#atmosphere-mini-name').textContent=$('#atmosphere-name').value||'Tu atmósfera';$('#atmosphere-mini-name').style.color=draft.titleColor;preview.querySelector('small').style.color=draft.color;preview.querySelector('small').textContent=draft.ornament}
function openAtmosphereDialog(edit){const preset=edit?atmospheres.get(activeAtmosphereId):null;editingAtmosphereId=preset?.id||null;atmosphereDraft={...(preset?.style||style)};$('#atmosphere-name').value=preset?.name||'';$('#atmosphere-default').checked=preset?.id===atmospheres.defaultId();$('#atmosphere-error').textContent='';$('#atmosphere-dialog-title').textContent=edit?'Personaliza tu atmósfera':'Guarda tu propia atmósfera';$('#atmosphere-dialog-note').textContent=edit?'Se conservarán los demás ajustes de esta atmósfera. Para guardar los cambios del panel, usa «Actualizar con diseño actual».':'Se guardará el diseño actual: fondo, papel, tipografía, márgenes, marco y adornos. El texto de la carta no se guarda en la atmósfera.';$$('[data-atmosphere]').forEach(input=>input.value=atmosphereDraft[input.dataset.atmosphere]);updateAtmospherePreview();$('#atmosphere-dialog').showModal();$('#atmosphere-name').focus()}
$('#edit-atmosphere').onclick=()=>openAtmosphereDialog(true);$('#save-atmosphere').onclick=()=>openAtmosphereDialog(false);$('#cancel-atmosphere').onclick=()=>$('#atmosphere-dialog').close();$('#atmosphere-name').oninput=updateAtmospherePreview;
$$('[data-atmosphere]').forEach(input=>input.oninput=()=>{atmosphereDraft[input.dataset.atmosphere]=input.value;updateAtmospherePreview()});
$('#atmosphere-form').onsubmit=e=>{e.preventDefault();try{const result=atmospheres.save({id:editingAtmosphereId,name:$('#atmosphere-name').value,style:atmosphereDraft,makeDefault:$('#atmosphere-default').checked});$('#atmosphere-dialog').close();applySaved(result,'Atmósfera guardada y aplicada.')}catch(error){$('#atmosphere-error').textContent=error.message}};
$('#update-atmosphere').onclick=()=>{const preset=atmospheres.get(activeAtmosphereId);if(!preset)return;applySaved(atmospheres.save({id:preset.id,name:preset.name,style,makeDefault:preset.id===atmospheres.defaultId()}),'Atmósfera actualizada con todo tu diseño.')};
$('#remove-atmosphere').onclick=()=>{const preset=atmospheres.get(activeAtmosphereId);if(!preset)return;const reset=!!original(preset.id);if(!window.confirm(reset?'¿Restaurar esta atmósfera a sus valores originales?':'¿Eliminar esta atmósfera guardada? Las cartas que ya compartiste se conservarán.'))return;applySaved(atmospheres.resetOrRemove(preset.id),reset?'Atmósfera original restaurada.':'Atmósfera eliminada.');};

const commands={bold:'toggleBold',italic:'toggleItalic',underline:'toggleUnderline',strike:'toggleStrike',bulletList:'toggleBulletList',orderedList:'toggleOrderedList',blockquote:'toggleBlockquote',horizontalRule:'setHorizontalRule',undo:'undo',redo:'redo'};
$$('[data-command]').forEach(b=>b.onclick=()=>editor.chain().focus()[commands[b.dataset.command]]().run());$('#block').onchange=e=>{e.target.value==='p'?editor.chain().focus().setParagraph().run():editor.chain().focus().setHeading({level:Number(e.target.value[1])}).run()};$('#selection-font').onchange=e=>{if(e.target.value)editor.chain().focus().setFontFamily(e.target.value).run()};$('#selection-size').onchange=e=>{if(e.target.value)editor.chain().focus().setFontSize(e.target.value+'px').run()};$('#text-color').onchange=e=>editor.chain().focus().setColor(e.target.value).run();$('#highlight-color').onchange=e=>editor.chain().focus().setBackgroundColor(e.target.value).run();$('#text-align').onchange=e=>editor.chain().focus().setTextAlign(e.target.value).run();$('#clear-format').onclick=()=>editor.chain().focus().unsetAllMarks().unsetTextAlign().run();
$('#add-table').onclick=()=>editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run();$$('[data-table]').forEach(b=>b.onclick=()=>editor.chain().focus()[b.dataset.table]().run());
function moveBlock(direction){const {state}=editor,index=state.selection.$from.index(0),nodes=[];state.doc.forEach(n=>nodes.push(n));const next=index+direction;if(next<0||next>=nodes.length){notify(direction<0?'Este bloque ya está al principio.':'Este bloque ya está al final.');return}[nodes[index],nodes[next]]=[nodes[next],nodes[index]];let pos=0;for(let i=0;i<next;i++)pos+=nodes[i].nodeSize;const tr=state.tr.replaceWith(0,state.doc.content.size,Fragment.fromArray(nodes));tr.setSelection(nodes[next].type.name==='image'?NodeSelection.create(tr.doc,pos):TextSelection.near(tr.doc.resolve(Math.min(pos+1,tr.doc.content.size))));editor.view.dispatch(closeHistory(tr));editor.view.focus()}
$('#move-up').onclick=()=>moveBlock(-1);$('#move-down').onclick=()=>moveBlock(1);
$('#link').onclick=()=>{$('#link-url').value=editor.getAttributes('link').href||'';$('#link-error').textContent='';$('#link-dialog').showModal();$('#link-url').focus()};$('#cancel-link').onclick=()=>$('#link-dialog').close();$('#unlink').onclick=()=>{editor.chain().focus().extendMarkRange('link').unsetLink().run();$('#link-dialog').close()};$('#link-form').onsubmit=e=>{e.preventDefault();const url=$('#link-url').value.trim();if(!/^(https?:\/\/|mailto:)/i.test(url)){$('#link-error').textContent='Usa https://, http:// o mailto:.';return}editor.chain().focus().extendMarkRange('link').setLink({href:url}).run();$('#link-dialog').close()};
$('#add-image').onclick=()=>{const selected=editor.isActive('image'),a=selected?editor.getAttributes('image'):{};imagePosition=selected?editor.state.selection.from:null;$('#image-url').value=a.src||'';$('#image-alt').value=a.alt||'';$('#image-width').value=a.imageWidth||100;$('#image-radius').value=a.imageRadius||0;$('#image-align').value=a.imageAlign||'center';$('#image-width-value').textContent=$('#image-width').value+'%';$('#image-radius-value').textContent=$('#image-radius').value+' px';$('#image-error').textContent='';$('#image-dialog').showModal()};$('#cancel-image').onclick=()=>$('#image-dialog').close();$('#image-width').oninput=e=>$('#image-width-value').textContent=e.target.value+'%';$('#image-radius').oninput=e=>$('#image-radius-value').textContent=e.target.value+' px';$('#image-form').onsubmit=e=>{e.preventDefault();const src=validImageUrl($('#image-url').value.trim());if(!src){$('#image-error').textContent='La imagen debe tener una dirección https:// o http:// válida.';return}const attrs={src,alt:$('#image-alt').value,imageWidth:Number($('#image-width').value),imageRadius:Number($('#image-radius').value),imageAlign:$('#image-align').value};if(imagePosition!==null)editor.chain().focus().setNodeSelection(imagePosition).updateAttributes('image',attrs).run();else editor.chain().focus().setImage(attrs).run();$('#image-dialog').close()};
function data(){return {v:2,title:'',markdown:toMarkdown(serializableHTML()),style:{...style}}}
function renderLetter(d,preview=false){reading={data:d,preview};style=cleanStyle(d.style);if(!preview)activeAtmosphereId=atmospheres.list().find(p=>JSON.stringify(p.style)===JSON.stringify(style))?.id||null;applyStyle();$('#read-title').textContent=d.title;$('#read-title').hidden=!d.title;$('#read-content').innerHTML=safeHTML(d.markdown);$('#composer').hidden=true;$('#reader').hidden=false;$('#back-edit').hidden=false;$('#back-edit').textContent=preview?'Volver a editar':'Editar una copia';$('#new-letter').hidden=preview;$('#reader-label').textContent=preview?'VISTA PREVIA':'UNA CARTA PARA TI';document.body.classList.add('reading');window.scrollTo(0,0)}
$('#preview').onclick=()=>{if(!hasLetterContent()){notify('Escribe unas palabras para ver tu carta.');editor.commands.focus();return}renderLetter(data(),true)};
$('#back-edit').onclick=()=>{if(reading&&!reading.preview){editor.commands.setContent(editableHTML(reading.data));history.replaceState(null,'',location.pathname+location.search)}reading=null;$('#reader').hidden=true;$('#composer').hidden=false;document.body.classList.remove('reading');invalidate();editor.commands.focus()};
function generate(){let d;try{d=data();if(!d.markdown.trim()){notify('Escribe algo antes de compartir tu carta.');return null}const url=new URL(location.href);url.search='';url.hash=encode(d);$('#share-url').value=url.href;$('#open-letter').href=url.href;$('#share-result').hidden=false;$('#link-length').textContent=url.href.length.toLocaleString('es')+' caracteres en el enlace';if(url.href.length>12000)notify('El enlace es largo. Algunas aplicaciones pueden recortarlo: comprueba que se envíe completo.');return url.href}catch(e){notify(e.message);return null}}
$('#generate').onclick=()=>{if(generate())$('#share-result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'})};$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText($('#share-url').value);notify('Enlace copiado con todo el diseño de tu carta.')}catch{$('#share-url').focus();$('#share-url').select();notify('Seleccionamos el enlace. Cópialo con el menú de tu dispositivo.')}};
function route(){if(/^#c[12]\./.test(location.hash)){try{renderLetter(decode(location.hash.slice(1)))}catch(e){$('#reader').hidden=true;$('#composer').hidden=false;document.body.classList.remove('reading');notify(e.message)}}else{$('#reader').hidden=true;$('#composer').hidden=false;document.body.classList.remove('reading');applyStyle()}}window.addEventListener('hashchange',route);applyStyle();updateUI();route();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'generate_letter_link',description:'Genera y muestra un enlace para compartir el contenido y diseño actuales de la carta.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length)throw Error('No se admiten parámetros.');if(!$('#reader').hidden)throw Error('Abre el editor antes de generar el enlace.');const url=generate();if(!url)throw Error('La carta no se puede compartir.');return {url}}})).catch(()=>{})}catch{}}
