import LZString from 'lz-string';
export const palettes={velvet:['#081229','#e1e8f7'],nocturne:['#101d35','#e0e8f6'],relic:['#172138','#e5eaf4']};
export const defaults={atmosphereName:'Tinta',theme:'velvet',color:'#a8bce8',font:'serif',size:18,ornaments:true,border:true,pageBg:'#00061a',pageEnd:'#142448',background:'solid',backgroundImage:'',paperBg:'#081229',textColor:'#e1e8f7',titleColor:'#e1e8f7',borderColor:'#526384',borderWidth:1,borderStyle:'solid',radius:2,padding:42,width:780,pageSpace:40,lineHeight:1.85,paragraphSpace:18,titleSize:32,titleAlign:'left',align:'center',shadow:30,transparent:false,signature:true,signatureStyle:'name',signatureText:'EmLetter',ornament:'✦',titleFont:'serif'};
const numeric={size:[12,48],borderWidth:[0,8],radius:[0,60],padding:[12,100],width:[320,1400],pageSpace:[0,160],lineHeight:[1,3],paragraphSpace:[0,60],titleSize:[18,96],shadow:[0,70]};
const choices={theme:Object.keys(palettes),font:['serif','mono','sans','cursive'],titleFont:['serif','mono','sans','cursive'],background:['solid','gradient','radial','lines','image'],borderStyle:['solid','dashed','dotted','double'],titleAlign:['left','center','right'],align:['left','center','right'],signatureStyle:['none','name','digital'],ornament:['✦','☾','✧','♡','†','—']};
export function validImageUrl(value){if(typeof value!=='string'||value.length>3000)return '';try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return ''}}
export function cleanStyle(input={}){const s={...defaults};if(!input||typeof input!=='object')return s;for(const k of Object.keys(s)){const v=input[k];if(k==='atmosphereName'){if(typeof v==='string'&&v.trim())s[k]=v.trim().slice(0,60)}else if(k==='signatureText'){if(typeof v==='string')s[k]=v.slice(0,80)}else if(k in numeric){const [min,max]=numeric[k];if(Number.isFinite(v))s[k]=Math.max(min,Math.min(max,v))}else if(k in choices){if(choices[k].includes(v))s[k]=v}else if(typeof s[k]==='boolean'){if(typeof v==='boolean')s[k]=v}else if(k==='backgroundImage'){s[k]=validImageUrl(v)}else if(/^#[0-9a-f]{6}$/i.test(v)){s[k]=v}}
// Older cards stored only the theme name, not their custom paper colors.
if(input.atmosphereName===undefined)s.atmosphereName=({velvet:'Tinta',nocturne:'Bruma',relic:'Ceniza'})[s.theme];if(input.paperBg===undefined)s.paperBg=palettes[s.theme][0];if(input.textColor===undefined)s.textColor=palettes[s.theme][1];if(input.titleColor===undefined)s.titleColor=s.textColor;if(input.signatureStyle===undefined)s.signatureStyle=input.signature===false?'none':'name';s.signature=s.signatureStyle!=='none';return s}
export function validate(data){if(!data||![1,2].includes(data.v)||typeof data.markdown!=='string'||data.markdown.length>200000||typeof data.title!=='string'||data.title.length>180)throw Error('Esta carta no tiene un formato válido o es demasiado extensa.');return {v:data.v,title:data.title,markdown:data.markdown,style:cleanStyle(data.style)}}
export function encode(data){return 'c2.'+LZString.compressToEncodedURIComponent(JSON.stringify({...validate(data),v:2}))}
export function decode(hash){if(hash.length>280000||!/^c[12]\./.test(hash))throw Error('El enlace de esta carta está incompleto o no es válido.');try{const json=LZString.decompressFromEncodedURIComponent(hash.slice(3));if(!json||json.length>260000)throw Error();return validate(JSON.parse(json))}catch{throw Error('No se pudo abrir la carta. Revisa que hayas copiado el enlace completo.')}}
